# Generated by Django 2.1.4 on 2018-12-05 17:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smurf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('age', models.CharField(max_length=200)),
                ('height', models.CharField(max_length=80)),
            ],
        ),
    ]
